organization_key     = "oyurch"
quality_gate_id      = "9"
group_name           = "members"
permission           = "admin"
sources              = "."
tests                = "tests"
coverage_report_paths = "./coverage.xml"